# Generated by Django 5.2.3 on 2025-09-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='preview',
            field=models.ImageField(upload_to='cars/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
